name: epam-platform-engineering-idp
description: >
  Deploy an API Gateway to process payloads and route service requests to dedicated queues with the necessary details for resource creation. Supports dependencies, retry logic, and reliable processing.
runtime:
  name: python
  options:
    toolchain: pip
    virtualenv: venv
config:
  pulumi:tags:
    value:
      pulumi:template: aws-python
